### ISSUE TITLE
sudo rake bootstrap uses the wrong file permissions

### ISSUE THREAD

**Issue by xfreebird** [fastlane/countdown#1]
Hi @KrauseFx,

On my machine I'm using the default ruby.

In the documentation it is stated that I should run:

``` bash
sudo rake bootstrap
```

but doing so it creates files with the wrong permissions.
Instead of my user, it is using `root`: 

``` bash
[nghimbovschi@home countdown (master)]$ ls -la
total 24
drwxr-xr-x  23 nghimbovschi  PowerUser   782 15 Sep 14:39 .
drwxr-xr-x   5 nghimbovschi  PowerUser   170 15 Sep 14:38 ..
drwxr-xr-x  13 nghimbovschi  PowerUser   442 15 Sep 14:38 .git
-rw-r--r--   1 nghimbovschi  PowerUser     2 15 Sep 14:38 .gitignore
-rw-r--r--   1 nghimbovschi  PowerUser  4064 15 Sep 14:38 README.md
-rw-r--r--   1 nghimbovschi  PowerUser  3433 15 Sep 14:38 Rakefile
drwxr-xr-x  21 root          PowerUser   714 15 Sep 14:39 boarding
drwxr-xr-x  20 root          PowerUser   680 15 Sep 14:46 cert
drwxr-xr-x  17 root          PowerUser   578 15 Sep 14:47 codes
drwxr-xr-x  21 root          PowerUser   714 15 Sep 14:48 credentials_manager
drwxr-xr-x  22 root          PowerUser   748 15 Sep 14:43 deliver
drwxr-xr-x  17 root          PowerUser   578 15 Sep 14:39 enhancer
drwxr-xr-x  24 root          PowerUser   816 15 Sep 14:41 fastlane
drwxr-xr-x  22 root          PowerUser   748 15 Sep 14:42 fastlane_core
drwxr-xr-x  21 root          PowerUser   714 15 Sep 14:44 frameit
drwxr-xr-x  24 root          PowerUser   816 15 Sep 14:47 gym
drwxr-xr-x  23 root          PowerUser   782 15 Sep 14:44 pem
drwxr-xr-x  22 root          PowerUser   748 15 Sep 14:48 pilot
drwxr-xr-x  17 root          PowerUser   578 15 Sep 14:46 produce
drwxr-xr-x  17 root          PowerUser   578 15 Sep 14:39 refresher
drwxr-xr-x  22 root          PowerUser   748 15 Sep 14:45 sigh
drwxr-xr-x  19 root          PowerUser   646 15 Sep 14:43 snapshot
drwxr-xr-x  25 root          PowerUser   850 15 Sep 14:49 spaceship
```

running the same command without the sudo command it fails when it is trying to run `gem install` to install the created gem. That is an expected behaviour.

**Comment by KrauseFx** [comment]
Oh, that's not good. So there should be a way to run `sudo` only for the gem install, but not for cloning, right?

**Comment by xfreebird** [comment]
Yes, but there is a catch.

`clone` and `bundle` should be run without `sudo`.

The problem appears when  `install` is run, because `rake install` will try to install the gem file, and without `sudo` it will fail.

But if run with `sudo`, it will leave the `pkg` folder with `root` permissions.

People with my setup would be recommended to run only `rake clone bundle` to have no side effects.

In the case when `sudo rake install` is run, the ruby script would have to to to changed to fix ownership of the new files to  current username `chmod -R <username> *`.

**Comment by xfreebird** [comment]
The only real solution I see here is to use `rbenv` or `rvm`
