### ISSUE TITLE
Error when doing rake bootstrap

### ISSUE THREAD

**Issue by knutigro** [fastlane/countdown#16]
Hi, I am totally new to Ruby but wanted to install the devtools to play around and see if I could add some small stuff. I got a problem though when doing `rake bootstrap`

Here is the console log:

```
...
Using fastlane 1.58.0
Bundle updated!
cd fastlane && rake install
fastlane 1.58.0 built to pkg/fastlane-1.58.0.gem.
rake aborted!
Couldn't install gem, run `gem install /Users/knutinge/Documents/SourceCode/Ruby/countdown/fastlane/pkg/fastlane-1.58.0.gem' for more detailed output
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:87:in `install_gem'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:44:in `block in install'
Tasks: TOP => install
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [cd fastlane && rake install...]
/Users/knutinge/Documents/SourceCode/Ruby/countdown/Rakefile:39:in `block (2 levels) in <top (required)>'
/Users/knutinge/Documents/SourceCode/Ruby/countdown/Rakefile:38:in `each'
/Users/knutinge/Documents/SourceCode/Ruby/countdown/Rakefile:38:in `block in <top (required)>'
/Users/knutinge/Documents/SourceCode/Ruby/countdown/Rakefile:13:in `block in <top (required)>'
Tasks: TOP => install
(See full trace by running task with --trace)
```

I then tried to do: `sudo gem install /Users/knutinge/Documents/SourceCode/Ruby/countdown/fastlane/pkg/fastlane-1.58.0.gem` like suggested. But got this Error:

```
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fastlane
```

Do you have any suggestions what I should do?

Greetings from Knut

**Comment by i2amsam** [comment]
Hi @knutigro looks like this may be a permissions issue.  What do you see if you add a `--verbose` to the end of your `gem install` command?

**Comment by KrauseFx** [comment]
Have you tried using rbenv or rvm? I think the documentation of this repo should be more clear to explain this as well, or offer a `sudo` mode

**Comment by knutigro** [comment]
Thank you @i2amsam and @KrauseFx  I did now install `rbenv` and it works like a charm :-)

**Comment by dr2050** [comment]
The issue with `fastlane` is solved by adding `-n /usr/local/bin` in the install or update line on El Capitan, the Destroyer.
