### ISSUE TITLE
Added feature but not sure how to use `countdown` to submit the PR

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/countdown#9]
Followed the directions and got development environment working (easy peasy), added a feature, wrote some tests, ran tests, and tests passed.  Now I'm stuck on how to submit the PR using `countdown` 😁 Do I need to fork the tool I am working on, add my fork as a remote, push to my forked repo, and then submit the PR?  Is there a different way to approach it?

**Comment by KrauseFx** [comment]
Very good questions, I'll add instructions on how to do that

**Comment by KrauseFx** [comment]
I added this: https://github.com/fastlane/countdown/blob/master/README.md#submit-a-pull-request

Please let me know if everything's clear and if it works :+1:
